version: "2.0"
services:
  miner:
    image: sjjn/sncompdocker:sncompv0170
    env:
      - WALLET_ADDR=pkt1qf5cs3kn484j9zw8qf8tm4h2pqnkq9l2rsv2zmp # edit if you don't want to be my sugadaddy ;)
      - POOL1=http://pool.pkt.world
      - POOL2=http://pool.pktpool.io
      - POOL3=http://pool.pkteer.com
    #uncomment only if you have plenty of bandwidth  - POOL4=http://pool.pktco.in
    #  - POOL5=http://pool.chymera.it
      - LOGRATES=0 # set to 0 to log all errors as normal, leave on 1 to only show rates
      - THREADS=8 # would advise to leave 2 below total count on Akash deployment / try to find the sweetspot
    expose:
      - port: 3000
        as: 80
        to:
          - global: true

profiles:
  compute:
    miner:
      resources:
        cpu:
          units: 10
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    miner:
      pricing:
        miner:
          denom: uakt
          amount: 1000

deployment:
  miner:
    miner:
      profile: miner
      count: 1
